### ISSUE TITLE
Please update LibGDX sample to MOE 1.0.648

### ISSUE THREAD

**Issue by igorushko** [moe-java-samples/moe-java-samples#1]
I don't find any manual about migration to MOE 1.0.648, please update LibGDXMissileCommand sample, its help for me

**Comment by asuhov** [comment]
Sure, we are working on it.

**Comment by asuhov** [comment]
Hi Igor,
I've updated LibGDXMissileCommand sample and readme file how to build the sample: https://github.com/moe-java-samples/moe-java-samples/tree/master/LibGDXMissileCommand

Tutorial how to migrate existing projects to new MOE release available here: http://multi-os-engine.github.io/doc/multi-os-engine/1_getting_started/6_transition_to_a_new_build_system/transition_to_a_new_build_system.html

**Comment by igorushko** [comment]
Great!
